---
output:
  pdf_document:
    keep_tex: true
    fig_caption: yes
    code-fold: true
    latex_engine: xelatex
geometry: margin=1in
---

<head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"></head>

::: {title}
# [POSC 2103--10A: Introduction to United States Government]{style="color:#DF3232;"}
:::

::: {style="display: flex; flex-direction: column; align-items: center; text-align: center;"}
::: {style="font-size: 20px;"}
Dr. Cameron Wimpy
:::

::: {style="font-size: 20px;"}
Fall 2023
:::
:::

</div>

<i class="fas fa-envelope" style="padding-left: 70px; margin-right: 5px;"></i> [cwimpy\@astate.edu](mailto:cwimpy@astate.edu) <i class="fas fa-globe" style="padding-left: 240px; margin-right: 5px;"></i> [cwimpy.com](http://cwimpy.com)

<i class="fas fa-hourglass" style="padding-left: 70px; margin-right: 5px;"></i> By Zoom as needed <i class="fas fa-clock" style="padding-left: 246px; margin-right: 5px;"></i> Online

<i class="fas fa-home" style="padding-left: 70px; margin-right: 5px;"></i> HSS: 3007C <i class="fas fa-location-arrow" style="padding-left: 300px; margin-right: 5px;"></i> Online

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
mon <- as.Date("2023-08-21")

advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," -- ",tfri)
 return(tmp)
}
```

# [Course Description]{style="color:#DF3232;"}

This course serves as an introduction to: **The constitution, government, and politics of the United States.** The main goal of this course is to help you understand the structure and processes of the American political system. This is accomplished by reading about and analyzing:

-   the key structures and institutions of government;
-   relevant political actors such as political parties, interest groups and the media;
-   the electoral process;
-   voters and voting behavior.

# [General Education Goal]{style="color:#DF3232;"}

-   **Developing a strong foundation in the social sciences**: Students should be aware of the diverse systems developed by humans to manage and structure our relationships with one another. Students should prepare for the full range of public and private roles they are expected to fulfill as citizens, decision-makers and human beings in a democratic America and in a global society.

# [Student Learning Outcomes]{style="color:#DF3232;"}

1.  Explain the processes and effects of individual and group behavior

2.  Analyze events in terms of the concepts and relational propositions generated by the social science tradition

3.  Have a working knowledge of the government of the United States

4.  Understand the challenges of governing in the United States

5.  Explain how individuals and groups interact to produce their collective experience

6.  Analyze empirical evidence to make reasoned arguments about government of the United States

\clearpage

# [Course Requirements]{style="color:#DF3232;"}

## [Textbook]{style="color:#DF3232;"}

This textbook is required. You can search for it online, in the bookstore, and view the publisher's website via this ISBN: [978-0190299903](http://global.oup.com/ushe/product/american-government-9780190299903). The book includes a student companion website that has additional materials to help you study and further explore government in the United States.

\hangindent=0.7cm

*Krutz, Glen (2021).* \emph{American Government}*. Houston, TX: OpenStax---Rice University.*

## [Technology]{style="color:#DF3232;"}

You will need to use your A-State email and have access to Canvas If there is any issue with these items you should me know by the second day of class.

## [Exams]{style="color:#DF3232;"}

There will be two multiple-choice exams. The exams will take place via Canvas (make sure you can access Canvas by the second day of class). Each exam will consist of 50 questions taken from the lectures and readings. The final exam is \underline{not} comprehensive.

## [Course Policies]{style="color:#DF3232;"}

These course policies are subject to change, but assume they are in effect unless you hear otherwise from Dr. Wimpy.

## [Academic Freedom]{style="color:#DF3232;"}

We are living in a particularly polarized period of American politics, and that means that some of us will often disagree with differing (but typically reasonable) points of view. Disagreement and debate is a healthy part of our political system so please be respectful of your classmates as they share their perspectives. Please know you have complete academic freedom to express your opinions and thoughts on U.S. Government. Having said that, any type of hateful or insulting discussion will not be tolerated.

## [Grading Policy]{style="color:#DF3232;"}

Your grade will consist of your performance on the exams along with your ability to participate in the class through attendance and discussions of course material/current events. The evaluation breakdown will be as follows:

| Item       | Weight |
|------------|--------|
| Discussion | 25%    |
| Exam #1    | 25%    |
| Exam #2    | 25%    |
| Quizzes    | 25%    |

The grading system will follow the [A-State convention](https://www.astate.edu/college/graduate-school/academic-policies/). Letter grades will be assigned as follows:

| Letter Grade | Range      |
|--------------|------------|
| A            | 89.5--100  |
| B            | 79.5--89.4 |
| C            | 69.5--79.4 |
| D            | 59.5--69.4 |
| F            | 00.0--59.4 |

## [Make-Up Exam Policy]{style="color:#DF3232;"}

There are no make-ups for missed exams unless there is a valid excuse. Don't bother asking.

## [Extra Credit/Grade Change Policy]{style="color:#DF3232;"}

I do not give extra credit and grades will only be changed in the event of a calculation error. Do not bother asking about anything else.

## [Attendance]{style="color:#DF3232;"}

## [Laptops, Phones, & Tablets]{style="color:#DF3232;"}

Laptops and tablets are allowed in the classroom insofar as they are used to take notes and/or accessing the online text (should you opt for the online edition). Phones are not allowed to be out during class time under any circumstances. If you have an emergency, please leave the class and take care of it. Otherwise it can wait. If I see abuse of the laptop/tablet policy I reserve the right to disallow these during class time unless there is a documented and approved exception.

## [Academic Dishonesty Policy]{style="color:#DF3232;"}

## [Access and Accomodations Policy]{style="color:#DF3232;"}

## [Copyright & Fair Use Statement]{style="color:#DF3232;"}

The materials used in this course are subject to copyright laws. For those materials which neither I nor ASU owns the copyright, I have either obtained a license for use or am using the materials in a manner that I reasonably believe is in compliance with the Fair Use exception to the copyright laws. The other materials used in this course are copyrighted. By this, I mean all materials generated for this class, which include but are not limited to syllabi, exams, lectures, quizzes, assignments, and any other document I post in Blackboard. Because these items are copyrighted, you do not have the right to copy and distribute any course materials unless I, or the document publishers, expressly grant permission.

\newpage

## [Tentative Class Schedule]{style="color:#DF3232;"}

Important: class readings are subject to change, contingent on mitigating circumstances and the progress we make as a class. Students are encouraged to check the Blackboard announcements section and any e-mails from me for updates.

## [`r advdate(mon, 1)`: Course Introduction, Topic Introduction (U.S. Government)]{style="color:#DF3232;"}

*Read:*

-   The Course Syllabus

-   Chapter 1

## [`r advdate(mon, 2)`: The Constitution]{style="color:#DF3232;"}

*Read:*

-   Chapter 2

## [`r advdate(mon, 3)`: Federalism]{style="color:#DF3232;"}

*Read:*

-   Chapter 3

## [`r advdate(mon, 4)`: Civil Liberties]{style="color:#DF3232;"}

*Read:*

-   Chapter 4
